# Generated by Django 2.2.2 on 2019-06-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20190611_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='pagerduty_event_class_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processtype',
            name='pagerduty_event_component_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processtype',
            name='pagerduty_event_group_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processtype',
            name='pagerduty_event_severity',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processtype',
            name='pagerduty_event_summary_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
