# Generated by Django 2.2.2 on 2019-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20190617_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_class_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_component_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_group_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_severity',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_summary_template',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
