# Generated by Django 2.2.2 on 2019-06-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0005_auto_20190617_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='pagerduty_enabled',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='pagerduty_event_class_template',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='pagerduty_event_component_template',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='pagerduty_event_group_template',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='pagerduty_event_severity',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='pagerduty_event_summary_template',
        ),
        migrations.CreateModel(
            name='PagerDutyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('api_token', models.CharField(max_length=1000)),
                ('default_event_summary_template', models.CharField(blank=True, max_length=1000)),
                ('default_event_severity', models.CharField(blank=True, max_length=1000)),
                ('default_event_component_template', models.CharField(blank=True, max_length=1000)),
                ('default_event_group_template', models.CharField(blank=True, max_length=1000)),
                ('default_event_class_template', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('pagerduty_event_summary_template', models.CharField(blank=True, max_length=1000)),
                ('pagerduty_event_severity', models.CharField(blank=True, max_length=1000)),
                ('pagerduty_event_component_template', models.CharField(blank=True, max_length=1000)),
                ('pagerduty_event_group_template', models.CharField(blank=True, max_length=1000)),
                ('pagerduty_event_class_template', models.CharField(blank=True, max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pagerduty_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.PagerDutyProfile')),
            ],
        ),
        migrations.AddField(
            model_name='processtype',
            name='alert_methods',
            field=models.ManyToManyField(to='processes.AlertMethod'),
        ),
    ]
