# Generated by Django 2.2.2 on 2019-06-23 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_auto_20190623_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='alert_methods',
            field=models.ManyToManyField(blank=True, to='processes.AlertMethod'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='aws_ecs_default_security_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='aws_ecs_supported_launch_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
