# Generated by Django 2.2.2 on 2019-06-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_auto_20190623_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processexecution',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
