# Generated by Django 2.2.2 on 2019-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_auto_20190630_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runenvironment',
            name='pagerduty_api_key',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='pagerduty_enabled',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='pagerduty_max_events_per_hour',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='pagerduty_max_events_per_minute',
        ),
        migrations.AddField(
            model_name='runenvironment',
            name='default_alert_methods',
            field=models.ManyToManyField(blank=True, to='processes.AlertMethod'),
        ),
    ]
