# Generated by Django 2.2.2 on 2019-07-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_runenvironment_aws_ecs_supported_launch_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processexecution',
            old_name='status_message',
            new_name='last_status_message',
        ),
    ]
