# Generated by Django 2.2.2 on 2019-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0016_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sort_title',
            field=models.CharField(max_length=64),
        ),
    ]
