# Generated by Django 2.2.2 on 2019-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0017_auto_20190710_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sort_title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
