# Generated by Django 2.2.2 on 2019-07-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0018_auto_20190710_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processexecution',
            old_name='expected_success_count',
            new_name='expected_count',
        ),
    ]
