# Generated by Django 2.2.2 on 2019-07-23 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0020_auto_20190723_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processexecution',
            name='aws_ecs_security_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None),
        ),
    ]
