# Generated by Django 2.2.2 on 2019-07-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0021_auto_20190723_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtype',
            old_name='default_max_attempts',
            new_name='default_max_retries',
        ),
        migrations.RenameField(
            model_name='processtype',
            old_name='project',
            new_name='project_url',
        ),
    ]
