# Generated by Django 2.2.2 on 2019-07-25 06:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0024_processexecution_aws_subnets'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_default_subnets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None),
        ),
    ]
