# Generated by Django 2.2.2 on 2019-07-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0026_processtype_aws_default_subnets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processexecution',
            old_name='aws_ecs_task_id',
            new_name='aws_ecs_task_arn',
        ),
    ]
