# Generated by Django 2.2.2 on 2019-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0027_auto_20190725_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='aws_ecs_main_container_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
