# Generated by Django 2.2.2 on 2019-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0028_processtype_aws_ecs_main_container_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='aws_scheduled_event_rule_arn',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
