# Generated by Django 2.2.2 on 2019-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0029_processtype_aws_scheduled_event_rule_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_events_role_arn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
