# Generated by Django 2.2.2 on 2019-07-27 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0030_runenvironment_aws_events_role_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='aws_event_target_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processtype',
            name='aws_scheduled_execution_rule_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='runenvironment',
            name='aws_default_subnets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
