# Generated by Django 2.2.2 on 2019-07-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0031_auto_20190727_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='aws_event_target_rule_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
