# Generated by Django 2.2.2 on 2019-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0032_processtype_aws_event_target_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_default_region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
