# Generated by Django 2.2.2 on 2019-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0033_runenvironment_aws_default_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_dedup_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='pagerduty_event_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
