# Generated by Django 2.2.2 on 2019-07-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0034_auto_20190728_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagerdutyprofile',
            old_name='api_token',
            new_name='integration_key',
        ),
    ]
