# Generated by Django 2.2.2 on 2019-07-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0035_auto_20190728_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerdutyprofile',
            name='default_event_severity',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], max_length=1000),
        ),
    ]
