# Generated by Django 2.2.2 on 2019-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0036_auto_20190729_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='pagerduty_event_severity',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pagerdutyprofile',
            name='default_event_severity',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], max_length=10),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='pagerduty_event_severity',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], max_length=10),
        ),
    ]
