# Generated by Django 2.2.2 on 2019-08-17 22:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0037_auto_20190729_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='environment_variables_overrides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
