# Generated by Django 2.2.2 on 2019-08-17 22:31

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0038_processtype_environment_variables_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(blank=True, max_length=1000)),
                ('max_age_seconds', models.IntegerField(blank=True, null=True)),
                ('default_max_retries', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('run_reason', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('marked_done_at', models.DateTimeField(blank=True, null=True)),
                ('kill_started_at', models.DateTimeField(blank=True, null=True)),
                ('kill_finished_at', models.DateTimeField(blank=True, null=True)),
                ('kill_error_code', models.IntegerField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('timed_out_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('killed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowProcessTypeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_age_seconds', models.IntegerField(blank=True, null=True)),
                ('default_max_retries', models.IntegerField(default=0)),
                ('environment_variables_overrides', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('allocated_cpu_units', models.IntegerField(blank=True, null=True)),
                ('allocated_memory_mb', models.IntegerField(blank=True, null=True)),
                ('ui_color', models.CharField(blank=True, max_length=16)),
                ('ui_center_margin_top', models.FloatField(blank=True, null=True)),
                ('ui_center_margin_left', models.FloatField(blank=True, null=True)),
                ('ui_icon_type', models.CharField(blank=True, max_length=50)),
                ('ui_scale', models.FloatField(blank=True, null=True)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('always', 'Always'), ('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('exit_code', 'Exit code'), ('threshold', 'Threshold'), ('custom', 'Custom'), ('default', 'Default')], max_length=20)),
                ('exit_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('threshold_property', models.CharField(choices=[('execution_time', 'Executiontime'), ('success_ratio', 'Successratio'), ('failure_ratio', 'Failureratio'), ('skipped_ratio', 'Skippedratio')], max_length=50)),
                ('threshold_comparator', models.CharField(choices=[('=', '='), ('≠', '≠'), ('<', '<'), ('≤', '≤'), ('>', '>'), ('≥', '≥')], max_length=2)),
                ('custom_expression', models.CharField(blank=True, max_length=5000)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('ui_color', models.CharField(blank=True, max_length=16)),
                ('ui_line_style', models.CharField(blank=True, max_length=50)),
                ('ui_scale', models.FloatField(blank=True, null=True)),
                ('from_workflow_process_type_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processes.WorkflowProcessTypeInstance')),
                ('to_workflow_process_type_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processes.WorkflowProcessTypeInstance')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransitionEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField()),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowExecution')),
                ('workflow_transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowTransition')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowProcessTypeInstanceExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessExecution')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowExecution')),
                ('workflow_process_type_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowProcessTypeInstance')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='latest_workflow_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processes.WorkflowExecution'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('name', 'created_by_group')},
        ),
    ]
