# Generated by Django 2.2.2 on 2019-08-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0039_auto_20190817_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowprocesstypeinstance',
            name='start_transition_condition',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('count_at_least', 'Count at least')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='threshold_comparator',
            field=models.CharField(blank=True, choices=[('=', '='), ('≠', '≠'), ('<', '<'), ('≤', '≤'), ('>', '>'), ('≥', '≥')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='threshold_property',
            field=models.CharField(blank=True, choices=[('execution_time', 'Executiontime'), ('success_ratio', 'Successratio'), ('failure_ratio', 'Failureratio'), ('skipped_ratio', 'Skippedratio')], max_length=50),
        ),
    ]
