# Generated by Django 2.2.2 on 2019-09-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0041_auto_20190818_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_assumed_role_external_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_process_type_instances', to='processes.Workflow'),
        ),
    ]
