# Generated by Django 2.2.2 on 2019-10-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0042_auto_20190907_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='max_concurrency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
