# Generated by Django 2.2.2 on 2019-10-02 08:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0043_workflow_max_concurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow_snapshot',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
