# Generated by Django 2.2.2 on 2019-10-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0044_workflowexecution_workflow_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowprocesstypeinstance',
            name='condition_count_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowprocesstypeinstance',
            name='condition_ratio_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowprocesstypeinstance',
            name='max_complete_executions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='workflowprocesstypeinstance',
            name='should_eval_transitions_after_first_execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstance',
            name='start_transition_condition',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('count_at_least', 'Count at least'), ('ratio_at_least', 'Ratio at least')], default='all', max_length=20),
        ),
    ]
