# Generated by Django 2.2.2 on 2019-10-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0045_auto_20191003_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtransitionevaluation',
            name='from_workflow_process_type_instance_execution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowProcessTypeInstanceExecution'),
        ),
    ]
