# Generated by Django 2.2.2 on 2019-10-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0046_workflowtransitionevaluation_from_workflow_process_type_instance_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowprocesstypeinstanceexecution',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
