# Generated by Django 2.2.2 on 2019-10-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0047_workflowprocesstypeinstanceexecution_is_latest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processexecution',
            options={'ordering': ['started_at']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workflowprocesstypeinstance',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workflowprocesstypeinstanceexecution',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflowtransitionevaluation',
            options={'ordering': ['evaluated_at']},
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertmethod',
            name='pagerduty_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.PagerDutyProfile'),
        ),
    ]
