# Generated by Django 2.2.2 on 2019-10-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0048_auto_20191009_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='is_service',
        ),
        migrations.AddField(
            model_name='processtype',
            name='service_instance_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
