# Generated by Django 2.2.2 on 2019-10-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0049_auto_20191011_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='aws_ecs_service_arn',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
