# Generated by Django 2.2.2 on 2019-10-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0051_runenvironment_aws_workflow_starter_lambda_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='scheduling_run_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.RunEnvironment'),
        ),
    ]
