# Generated by Django 2.2.2 on 2019-11-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0054_auto_20191029_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowprocesstypeinstanceexecution',
            name='process_execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessExecution'),
        ),
    ]
