# Generated by Django 2.2.2 on 2019-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0055_auto_20191104_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_workflow_starter_access_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
