# Generated by Django 2.2.2 on 2019-11-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0060_processexecutionalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processexecutionalert',
            name='pagerduty_event_dedup_key',
        ),
    ]
