# Generated by Django 2.2.2 on 2019-11-12 22:19

from django.db import migrations, models
import processes.models.alert_send_status


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0062_processexecutionalert_send_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processexecution',
            name='pagerduty_event_severity',
        ),
        migrations.RemoveField(
            model_name='processexecutionalert',
            name='error_code',
        ),
        migrations.AddField(
            model_name='processexecutionalert',
            name='send_status',
            field=models.IntegerField(blank=True, default=processes.models.alert_send_status.AlertSendStatus(0), null=True),
        ),
    ]
