# Generated by Django 2.2.2 on 2019-11-13 02:58

from django.db import migrations, models
import django.db.models.deletion
import processes.models.alert_send_status


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0064_auto_20191112_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecutionAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('send_status', models.IntegerField(blank=True, default=processes.models.alert_send_status.AlertSendStatus(0), null=True)),
                ('send_result', models.CharField(blank=True, max_length=50000)),
                ('error_message', models.CharField(blank=True, max_length=50000)),
                ('for_latest_execution', models.BooleanField(default=True)),
                ('alert_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.AlertMethod')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowExecution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
