# Generated by Django 2.2.2 on 2019-11-23 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0065_workflowexecutionalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecutionalert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecutionalert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstance',
            name='failure_behavior',
            field=models.CharField(choices=[('always_fail_workflow', 'Always fail workflow'), ('fail_workflow_if_unhandled', 'Fail workflow if unhandled'), ('ignore', 'Ignore')], default='fail_workflow_if_unhandled', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstance',
            name='timeout_behavior',
            field=models.CharField(choices=[('always_fail_workflow', 'Always fail workflow'), ('always_timeout_workflow', 'Always timeout workflow'), ('fail_workflow_if_unhandled', 'Fail workflow if unhandled'), ('timeout_workflow_if_unhandled', 'Timeout workflow if unhandled'), ('ignore', 'Ignore')], default='timeout_workflow_if_unhandled', max_length=50),
        ),
    ]
