# Generated by Django 2.2.2 on 2019-11-23 07:23

from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def gen_pea_uuid(apps, schema_editor):
    ProcessExecutionAlert = apps.get_model('processes', 'ProcessExecutionAlert')
    for row in ProcessExecutionAlert.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


def gen_wea_uuid(apps, schema_editor):
    WorkflowExecutionAlert = apps.get_model('processes', 'WorkflowExecutionAlert')
    for row in WorkflowExecutionAlert.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0066_auto_20191123_0709'),
    ]

    operations = [
        migrations.RunPython(gen_pea_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_wea_uuid, reverse_code=migrations.RunPython.noop),
    ]
