# Generated by Django 2.2.2 on 2019-11-23 07:23

from django.db import migrations, models

import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0067_auto_20191123_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processexecutionalert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowexecutionalert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
