# Generated by Django 2.2.2 on 2019-11-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0069_missingscheduledprocessexecution_missingscheduledprocessexecutionalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmethod',
            name='error_severity_on_missing_execution',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], default='error', max_length=10),
        ),
        migrations.AddField(
            model_name='alertmethod',
            name='error_severity_on_missing_heartbeat',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], default='warning', max_length=10),
        ),
        migrations.AddField(
            model_name='alertmethod',
            name='error_severity_on_service_down',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('error', 'error'), ('warning', 'warning'), ('info', 'info')], default='error', max_length=10),
        ),
    ]
