# Generated by Django 2.2.2 on 2019-11-25 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0070_auto_20191124_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='schedule_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
