# Generated by Django 2.2.2 on 2019-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0071_processtype_schedule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='schedule_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
