# Generated by Django 2.2.2 on 2019-11-28 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import processes.models.alert_send_status
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0072_auto_20191125_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingScheduledWorkflowExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expected_execution_at', models.DateTimeField()),
                ('schedule', models.CharField(max_length=1000)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='schedule_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MissingScheduledWorkflowExecutionAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('send_status', models.IntegerField(blank=True, default=processes.models.alert_send_status.AlertSendStatus(0), null=True)),
                ('send_result', models.CharField(blank=True, max_length=50000)),
                ('error_message', models.CharField(blank=True, max_length=50000)),
                ('alert_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.AlertMethod')),
                ('missing_scheduled_workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.MissingScheduledWorkflowExecution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='missingscheduledworkflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.Workflow'),
        ),
    ]
