# Generated by Django 2.2.2 on 2019-11-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0073_auto_20191128_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='schedule_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
