# Generated by Django 2.2.2 on 2019-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0075_delayedprocessstartalert_delayedprocessstartdetectionevent_heartbeatdetectionalert_heartbeatdetectio'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='max_heartbeat_lateness_seconds',
            field=models.IntegerField(blank=True, default=120, null=True),
        ),
        migrations.AddField(
            model_name='processtype',
            name='max_manual_start_delay_seconds',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
    ]
