# Generated by Django 2.2.2 on 2019-12-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0076_auto_20191210_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeatdetectionevent',
            name='expected_heartbeat_at',
            field=models.DateTimeField(null=True),
        ),
    ]
