# Generated by Django 2.2.2 on 2019-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0077_auto_20191211_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingscheduledprocessexecution',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='missingscheduledworkflowexecution',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
