# Generated by Django 2.2.2 on 2019-12-14 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0078_auto_20191213_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayedprocessstartdetectionevent',
            name='resolving',
        ),
        migrations.RemoveField(
            model_name='heartbeatdetectionevent',
            name='resolving',
        ),
        migrations.AddField(
            model_name='delayedprocessstartdetectionevent',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='heartbeatdetectionevent',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='delayedprocessstartdetectionevent',
            name='expected_started_before',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
