# Generated by Django 2.2.2 on 2019-12-14 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0079_auto_20191214_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeatdetectionevent',
            name='expected_heartbeat_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
