# Generated by Django 2.2.2 on 2019-12-17 07:09

from django.db import migrations, models
import django.db.models.deletion
import processes.models.alert_send_status
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0080_auto_20191214_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='min_service_instance_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InsufficientServiceInstancesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interval_start_at', models.DateTimeField()),
                ('interval_end_at', models.DateTimeField()),
                ('detected_concurrency', models.IntegerField()),
                ('required_concurrency', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType')),
            ],
        ),
        migrations.CreateModel(
            name='InsufficientServiceInstancesAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('send_status', models.IntegerField(blank=True, default=processes.models.alert_send_status.AlertSendStatus(0), null=True)),
                ('send_result', models.CharField(blank=True, max_length=50000)),
                ('error_message', models.CharField(blank=True, max_length=50000)),
                ('alert_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.AlertMethod')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.InsufficientServiceInstancesEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
