# Generated by Django 2.2.2 on 2019-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0082_auto_20191219_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='aws_ecs_assign_public_ip',
            field=models.BooleanField(null=True),
        ),
    ]
