# Generated by Django 2.2.2 on 2020-01-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0083_processexecution_aws_ecs_assign_public_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_container_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_container_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_health_check_grace_period_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_target_group_arn',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
