# Generated by Django 2.2.2 on 2020-01-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0084_auto_20200104_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsEcsServiceLoadBalancerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group_arn', models.CharField(max_length=1000)),
                ('container_name', models.CharField(blank=True, max_length=1000)),
                ('container_port', models.IntegerField()),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType')),
            ],
        ),
    ]
