# Generated by Django 2.2.2 on 2020-01-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0086_auto_20200125_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_container_name',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_container_port',
        ),
        migrations.RemoveField(
            model_name='processtype',
            name='aws_ecs_service_load_balancer_target_group_arn',
        ),
    ]
