# Generated by Django 2.2.2 on 2020-02-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0087_auto_20200125_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtype',
            old_name='max_heartbeat_lateness_seconds',
            new_name='max_heartbeat_lateness_before_alert_seconds',
        ),
        migrations.AlterField(
            model_name='awsecsserviceloadbalancerdetails',
            name='process_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_ecs_service_load_balancer_details_set', to='processes.ProcessType'),
        ),
    ]
