# Generated by Django 2.2.2 on 2020-02-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0090_auto_20200205_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='max_manual_start_delay_before_abandonment_seconds',
            field=models.IntegerField(blank=True, default=1200, null=True),
        ),
    ]
