# Generated by Django 2.2.2 on 2020-03-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0091_processtype_max_manual_start_delay_before_abandonment_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTypeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_template', models.CharField(max_length=5000)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_by_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType')),
            ],
            options={
                'unique_together': {('name', 'process_type', 'created_by_group')},
            },
        ),
    ]
