# Generated by Django 2.2.2 on 2020-03-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0092_processtypelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtypelink',
            old_name='url_template',
            new_name='link_url_template',
        ),
    ]
