# Generated by Django 2.2.2 on 2020-03-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0093_auto_20200308_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtypelink',
            name='icon_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
