# Generated by Django 2.2.2 on 2020-03-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0094_processtypelink_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtypelink',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
