# Generated by Django 2.2.2 on 2020-03-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0095_processtypelink_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtypelink',
            options={'ordering': ['rank']},
        ),
    ]
