# Generated by Django 2.2.2 on 2020-04-12 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0098_auto_20200325_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='allocated_cpu_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='allocated_memory_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='default_max_retries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='heartbeat_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='max_age_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='max_heartbeat_lateness_before_abandonment_seconds',
            field=models.IntegerField(blank=True, default=600, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='max_heartbeat_lateness_before_alert_seconds',
            field=models.IntegerField(blank=True, default=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='max_manual_start_delay_before_abandonment_seconds',
            field=models.IntegerField(blank=True, default=1200, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='max_manual_start_delay_before_alert_seconds',
            field=models.IntegerField(blank=True, default=600, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='min_service_instance_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='service_instance_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
