# Generated by Django 2.2.2 on 2020-04-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0099_auto_20200412_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='process_version_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
