# Generated by Django 2.2.2 on 2020-04-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0100_processexecution_process_version_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processexecution',
            old_name='process_version',
            new_name='process_version_number',
        ),
        migrations.RenameField(
            model_name='processexecution',
            old_name='process_hash',
            new_name='process_version_signature',
        ),
    ]
