# Generated by Django 2.2.12 on 2020-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0102_processexecution_heartbeat_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='api_max_retries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='api_max_retries_for_final_update',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='api_max_retries_for_process_creation_conflict',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='api_retry_delay_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='api_timeout_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='command',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='deployment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='is_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='is_status_listener_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='max_conflicting_age_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process_max_concurrency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process_max_retries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process_retry_delay_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process_timeout_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
