# Generated by Django 2.2.12 on 2020-04-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0103_auto_20200418_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='api_base_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='api_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='prevent_offline_execution',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process_termination_grace_period_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='schedule',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='status_update_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='status_update_message_max_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='status_update_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='wrapper_log_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
