# Generated by Django 2.2.12 on 2020-04-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0105_auto_20200419_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processexecution',
            name='is_status_listener_enabled',
        ),
    ]
