# Generated by Django 2.2.12 on 2020-04-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0106_remove_processexecution_is_status_listener_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='embedded_mode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
