# Generated by Django 2.2.12 on 2020-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0107_processexecution_embedded_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processexecution',
            name='debug_log_tail',
            field=models.CharField(blank=True, max_length=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='deployment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='error_log_tail',
            field=models.CharField(blank=True, max_length=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='hostname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='last_status_message',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='process_command',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='process_version_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='process_version_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='schedule',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='wrapper_log_level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='wrapper_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
