# Generated by Django 2.2.12 on 2020-06-13 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0109_auto_20200423_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runenvironment',
            name='aws_ecs_default_security_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
