# Generated by Django 2.2.12 on 2020-07-19 06:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0110_auto_20200613_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('cc_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('bcc_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('subject_template', models.CharField(blank=True, max_length=1000)),
                ('body_template', models.CharField(blank=True, max_length=10000)),
                ('created_by_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'created_by_group')},
            },
        ),
        migrations.AddField(
            model_name='alertmethod',
            name='email_notification_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.EmailNotificationProfile'),
        ),
    ]
