# Generated by Django 2.2.14 on 2020-08-04 00:48

from django.db import migrations
#from django.contrib.postgres.operations import CryptoExtension

class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0113_auto_20200804_0023'),
    ]

    operations = [
        # May have uncomment this out for tests to work
        #CryptoExtension(),
        migrations.RunSQL(
                "UPDATE processes_saastoken SET uuid=gen_random_uuid() where uuid IS NULL;",
                reverse_sql='',
        ),
    ]
