# Generated by Django 2.2.14 on 2020-08-04 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0114_auto_20200804_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saastoken',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
