# Generated by Django 2.2.14 on 2020-08-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0116_usergroupaccesslevel_userrunenvironmentaccesslevel'),
    ]

    operations = [
        migrations.RunSQL(sql="""
INSERT INTO processes_usergroupaccesslevel (
    user_id, group_id, access_level, created_at, updated_at)
SELECT user_id, group_id, 1000, current_timestamp, current_timestamp
FROM auth_user_groups
ON CONFLICT DO NOTHING
""",
                reverse_sql=migrations.RunSQL.noop),
    ]
