# Generated by Django 2.2.14 on 2020-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0119_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='group_access_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
