# Generated by Django 2.2.14 on 2020-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0120_auto_20200815_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='to_email',
            field=models.EmailField(max_length=1000),
        ),
    ]
