# Generated by Django 2.2.14 on 2020-08-16 20:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0121_auto_20200816_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationprofile',
            name='bcc_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='emailnotificationprofile',
            name='cc_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='emailnotificationprofile',
            name='to_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
