# Generated by Django 2.2.14 on 2020-08-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0122_auto_20200816_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='saastoken',
            name='access_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='saastoken',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='saastoken',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
