# Generated by Django 2.2.14 on 2020-08-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0123_auto_20200821_0549'),
    ]

    operations = [
migrations.RunSQL(sql="""
UPDATE processes_saastoken SET access_level = (
  SELECT COALESCE(MAX(ugal.access_level), 1) FROM processes_usergroupaccesslevel ugal
  WHERE ugal.user_id = processes_saastoken.user_id
  AND ugal.group_id = processes_saastoken.group_id
)
""",
                reverse_sql=migrations.RunSQL.noop),
    ]
