# Generated by Django 2.2.14 on 2020-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0124_set_saas_token_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saastoken',
            name='access_level',
            field=models.IntegerField(default=1),
        ),
    ]
