# Generated by Django 2.2.14 on 2020-11-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0131_auto_20201107_2316'),
    ]

    operations = [
        migrations.RunSQL(
                "UPDATE processes_workflow SET run_environment_id = scheduling_run_environment_id WHERE run_environment_id IS NULL;",
                reverse_sql='',
        ),
    ]
