# Generated by Django 2.2.14 on 2020-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0132_auto_20201108_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='aws_ecs_default_assign_public_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='aws_ecs_default_execution_role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
