# Generated by Django 2.2.14 on 2020-12-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0133_auto_20201222_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('duration_days', models.IntegerField()),
                ('usd_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.IntegerField()),
                ('max_api_keys', models.IntegerField()),
                ('max_api_credits_per_month', models.BigIntegerField()),
                ('max_tasks', models.IntegerField()),
                ('max_task_execution_concurrency', models.IntegerField()),
                ('max_task_execution_history_items', models.IntegerField()),
                ('max_workflows', models.IntegerField()),
                ('max_workflow_execution_concurrency', models.IntegerField()),
                ('max_workflow_task_instances', models.IntegerField()),
                ('max_workflow_execution_history_items', models.IntegerField()),
                ('max_alerts_per_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.SubscriptionPlan')),
            ],
        ),
    ]
