# Generated by Django 2.2.14 on 2020-12-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0134_subscription_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
