# Generated by Django 2.2.14 on 2021-01-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0135_auto_20201231_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awsecsserviceloadbalancerdetails',
            old_name='process_type',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='delayedprocessstartdetectionevent',
            old_name='process_execution',
            new_name='task_execution',
        ),
        migrations.RenameField(
            model_name='heartbeatdetectionevent',
            old_name='process_execution',
            new_name='task_execution',
        ),
        migrations.RenameField(
            model_name='insufficientserviceinstancesevent',
            old_name='process_type',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='missingscheduledprocessexecution',
            old_name='process_type',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='processexecution',
            old_name='process_type',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='processexecution',
            old_name='process_version_number',
            new_name='task_version_number',
        ),
        migrations.RenameField(
            model_name='processexecution',
            old_name='process_version_signature',
            new_name='task_version_signature',
        ),
        migrations.RenameField(
            model_name='processexecution',
            old_name='process_version_text',
            new_name='task_version_text',
        ),
        migrations.RenameField(
            model_name='processtype',
            old_name='latest_process_execution',
            new_name='latest_task_execution',
        ),
        migrations.RenameField(
            model_name='processtypelink',
            old_name='process_type',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='workflowprocesstypeinstance',
            old_name='process_type',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='workflowprocesstypeinstance',
            old_name='use_process_type_alert_methods',
            new_name='use_task_alert_methods',
        ),
        migrations.RenameField(
            model_name='workflowprocesstypeinstanceexecution',
            old_name='process_execution',
            new_name='task_execution',
        ),
        migrations.RenameField(
            model_name='workflowprocesstypeinstanceexecution',
            old_name='workflow_process_type_instance',
            new_name='workflow_task_instance',
        ),
        migrations.RenameField(
            model_name='workflowtransition',
            old_name='from_workflow_process_type_instance',
            new_name='from_workflow_task_instance',
        ),
        migrations.RenameField(
            model_name='workflowtransition',
            old_name='to_workflow_process_type_instance',
            new_name='to_workflow_task_instance',
        ),
        migrations.RenameField(
            model_name='workflowtransitionevaluation',
            old_name='from_workflow_process_type_instance_execution',
            new_name='from_workflow_task_instance_execution',
        ),
        migrations.AlterField(
            model_name='awsecsserviceloadbalancerdetails',
            name='task',
            field=models.ForeignKey(db_column='process_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='aws_ecs_service_load_balancer_details_set', to='processes.ProcessType'),
        ),
        migrations.AlterField(
            model_name='delayedprocessstartdetectionevent',
            name='task_execution',
            field=models.ForeignKey(db_column='process_execution_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessExecution'),
        ),
        migrations.AlterField(
            model_name='heartbeatdetectionevent',
            name='task_execution',
            field=models.ForeignKey(db_column='process_execution_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessExecution'),
        ),
        migrations.AlterField(
            model_name='insufficientserviceinstancesevent',
            name='task',
            field=models.ForeignKey(db_column='process_type_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType'),
        ),
        migrations.AlterField(
            model_name='missingscheduledprocessexecution',
            name='task',
            field=models.ForeignKey(db_column='process_type_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType'),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='task',
            field=models.ForeignKey(db_column='process_type_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType'),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='task_version_number',
            field=models.BigIntegerField(blank=True, db_column='process_version_number', null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='task_version_signature',
            field=models.CharField(blank=True, db_column='process_version_signature', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='task_version_text',
            field=models.CharField(blank=True, db_column='process_version_text', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='latest_task_execution',
            field=models.OneToOneField(blank=True, db_column='latest_process_execution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processes.ProcessExecution'),
        ),
        migrations.AlterField(
            model_name='processtypelink',
            name='task',
            field=models.ForeignKey(db_column='process_type_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType'),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstance',
            name='task',
            field=models.ForeignKey(db_column='process_type_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessType'),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstance',
            name='use_task_alert_methods',
            field=models.BooleanField(db_column='use_process_type_alert_methods', default=False),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstanceexecution',
            name='task_execution',
            field=models.OneToOneField(db_column='process_execution_id', on_delete=django.db.models.deletion.CASCADE, to='processes.ProcessExecution'),
        ),
        migrations.AlterField(
            model_name='workflowprocesstypeinstanceexecution',
            name='workflow_task_instance',
            field=models.ForeignKey(db_column='workflow_process_type_instance_id', on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowProcessTypeInstance'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='from_workflow_task_instance',
            field=models.ForeignKey(db_column='from_workflow_process_type_instance_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processes.WorkflowProcessTypeInstance'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='to_workflow_task_instance',
            field=models.ForeignKey(db_column='to_workflow_process_type_instance_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processes.WorkflowProcessTypeInstance'),
        ),
        migrations.AlterField(
            model_name='workflowtransitionevaluation',
            name='from_workflow_task_instance_execution',
            field=models.ForeignKey(db_column='from_workflow_process_type_instance_execution_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.WorkflowProcessTypeInstanceExecution'),
        ),
        migrations.AlterUniqueTogether(
            name='processtypelink',
            unique_together={('name', 'task', 'created_by_group')},
        ),
    ]
