# Generated by Django 2.2.14 on 2021-01-03 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0136_auto_20210103_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessType',
            new_name='Task',
        ),
        migrations.AlterModelTable(
            name='task',
            table='processes_processtype',
        ),
    ]
