# Generated by Django 2.2.14 on 2021-01-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0137_auto_20210103_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessExecution',
            new_name='TaskExecution',
        ),
        migrations.RenameField(
            model_name='processexecutionalert',
            old_name='process_execution',
            new_name='task_execution',
        ),
        migrations.AlterField(
            model_name='processexecutionalert',
            name='task_execution',
            field=models.ForeignKey(db_column='process_execution_id', on_delete=django.db.models.deletion.CASCADE, to='processes.TaskExecution'),
        ),
        migrations.AlterModelTable(
            name='taskexecution',
            table='processes_processexecution',
        ),
    ]
