# Generated by Django 2.2.14 on 2021-01-04 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processes.models.alert_send_status
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('processes', '0138_auto_20210103_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessTypeLink',
            new_name='TaskLink',
        ),
        migrations.AlterModelTable(
            name='tasklink',
            table='processes_processtypelink',
        ),
        migrations.RenameModel(
            old_name='MissingScheduledProcessExecution',
            new_name='MissingScheduledTaskExecution',
        ),
        migrations.AlterModelTable(
            name='missingscheduledtaskexecution',
            table='processes_missingscheduledprocessexecution',
        ),
        migrations.RenameModel(
            old_name='MissingScheduledProcessExecutionAlert',
            new_name='MissingScheduledTaskExecutionAlert',
        ),
        migrations.AlterModelTable(
            name='missingscheduledtaskexecutionalert',
            table='processes_missingscheduledprocessexecutionalert',
        ),
        migrations.RenameModel(
            old_name='ProcessExecutionAlert',
            new_name='TaskExecutionAlert',
        ),
        migrations.AlterModelTable(
            name='taskexecutionalert',
            table='processes_processexecutionalert',
        ),
        migrations.RenameField(
            model_name='missingscheduledtaskexecutionalert',
            old_name='missing_scheduled_process_execution',
            new_name='missing_scheduled_task_execution',
        ),
        migrations.AlterField(
            model_name='missingscheduledtaskexecutionalert',
            name='missing_scheduled_task_execution',
            field=models.ForeignKey(db_column='missing_scheduled_process_execution_id',
                    on_delete=django.db.models.deletion.CASCADE, to='processes.MissingScheduledTaskExecution'),
        ),
    ]
