# Generated by Django 2.2.14 on 2021-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0140_auto_20210104_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskexecution',
            old_name='process_max_concurrency',
            new_name='task_max_concurrency',
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task_max_concurrency',
            field=models.IntegerField(blank=True, db_column='process_max_concurrency', null=True),
        ),
    ]
