# Generated by Django 2.2.14 on 2021-01-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0141_auto_20210104_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskexecution',
            old_name='api_timeout_seconds',
            new_name='api_request_timeout_seconds',
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='api_request_timeout_seconds',
            field=models.IntegerField(blank=True, db_column='api_timeout_seconds', null=True),
        ),
    ]
