# Generated by Django 2.2.14 on 2021-02-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0143_auto_20210131_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskexecution',
            old_name='api_task_execution_creation_retry_delay_seconds',
            new_name='api_task_execution_creation_conflict_retry_delay_seconds',
        ),
    ]
