# Generated by Django 2.2.14 on 2021-03-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0144_auto_20210203_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, default='1.3.0', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, default='1.3.0', max_length=10),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='aws_ecs_platform_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
