# Generated by Django 2.2.19 on 2021-03-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0145_auto_20210303_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='passive',
            field=models.BooleanField(default=False),
        ),
    ]
