# Generated by Django 2.2.19 on 2021-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0146_task_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_method_type',
            field=models.CharField(default='AWS ECS', max_length=100),
        ),
    ]
