# Generated by Django 2.2.19 on 2021-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0148_set_marked_done_at_on_abandoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_deploy_maximum_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_deploy_minimum_healthy_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_deploy_rollback_on_failure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_enable_ecs_managed_tags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_force_new_deployment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_propagate_tags',
            field=models.CharField(blank=True, choices=[('TASK_DEFINITION', 'TASK_DEFINITION'), ('SERVICE', 'SERVICE')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_instance_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='scheduled_instance_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runenvironment',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, choices=[('1.3.0', '1.3.0'), ('1.4.0', '1.4.0'), ('LATEST', 'LATEST')], default='1.3.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, choices=[('1.3.0', '1.3.0'), ('1.4.0', '1.4.0'), ('LATEST', 'LATEST')], default='1.3.0', max_length=10),
        ),
    ]
