# Generated by Django 2.2.19 on 2021-05-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0149_auto_20210511_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_ecs_enable_ecs_managed_tags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_ecs_enable_ecs_managed_tags',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
