# Generated by Django 2.2.19 on 2021-05-12 00:31

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0150_auto_20210512_0025'),
    ]

    operations = [
        HStoreExtension(),
    ]
