# Generated by Django 2.2.19 on 2021-05-13 07:57

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0151_add_hstore_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='aws_tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='aws_tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
