# Generated by Django 2.2.19 on 2021-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0152_auto_20210513_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_deploy_enable_circuit_breaker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
