# Generated by Django 2.2.19 on 2021-05-15 15:17

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0153_task_aws_ecs_service_deploy_enable_circuit_breaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='aws_ecs_service_tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
