# Generated by Django 3.2.6 on 2021-08-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0154_task_aws_ecs_service_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='environment_variables_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='other_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='environment_variables_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='other_instance_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='other_runtime_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowtaskinstance',
            name='environment_variables_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
