# Generated by Django 3.2.6 on 2021-08-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0156_remove_userprofile_sort_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmethod',
            name='pagerduty_event_component_template',
        ),
    ]
