# Generated by Django 3.2.6 on 2021-08-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('processes', '0157_remove_alertmethod_pagerduty_event_component_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_credits_used_current_month', models.BigIntegerField(default=0)),
                ('api_credits_used_previous_month', models.BigIntegerField(default=0)),
                ('api_last_used_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_info', to='auth.group')),
            ],
        ),
    ]
