# Generated by Django 3.2.6 on 2021-11-09 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0159_auto_20210830_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmethod',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='alertmethod',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailnotificationprofile',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='emailnotificationprofile',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagerdutyprofile',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='pagerdutyprofile',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runenvironment',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='runenvironment',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_alerts_per_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_api_credits_per_month',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_api_keys',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_task_execution_concurrency',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_task_execution_history_items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_tasks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_workflow_execution_concurrency',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_workflow_execution_history_items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_workflow_task_instances',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_workflows',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='default_max_retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_heartbeat_lateness_before_abandonment_seconds',
            field=models.PositiveIntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_heartbeat_lateness_before_alert_seconds',
            field=models.PositiveIntegerField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_manual_start_delay_before_abandonment_seconds',
            field=models.PositiveIntegerField(blank=True, default=1200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_manual_start_delay_before_alert_seconds',
            field=models.PositiveIntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='min_service_instance_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='current_cpu_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='current_memory_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='heartbeat_interval_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='mean_cpu_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='mean_memory_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='timed_out_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasklink',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='tasklink',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowtaskinstanceexecution',
            name='is_latest',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workflowtaskinstanceexecution',
            name='task_execution',
            field=models.OneToOneField(db_column='process_execution_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='processes.taskexecution'),
        ),
        migrations.AlterField(
            model_name='workflowtaskinstanceexecution',
            name='workflow_execution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='processes.workflowexecution'),
        ),
        migrations.AlterField(
            model_name='workflowtaskinstanceexecution',
            name='workflow_task_instance',
            field=models.ForeignKey(db_column='workflow_process_type_instance_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='processes.workflowtaskinstance'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
