# Generated by Django 3.2.8 on 2022-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0160_auto_20211109_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_method_capability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='max_postponed_failure_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='max_postponed_missing_execution_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='max_postponed_timeout_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='min_missing_execution_delay_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='postponed_failure_before_success_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='postponed_missing_execution_before_start_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='postponed_timeout_before_success_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='should_clear_failure_alerts_on_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='should_clear_timeout_alerts_on_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='max_postponed_failure_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='max_postponed_missing_execution_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='max_postponed_timeout_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='min_missing_execution_delay_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='postponed_failure_before_success_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='postponed_missing_execution_before_start_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='postponed_timeout_before_success_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='should_clear_failure_alerts_on_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='should_clear_timeout_alerts_on_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='execution_method_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='default_max_retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='max_age_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
