# Generated by Django 3.2.13 on 2022-06-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0162_rename_execution_method_capability_task_execution_method_capability_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='infrastructure_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='infrastructure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduling_provider_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduling_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='service_provider_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='service_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
