# Generated by Django 3.2.13 on 2022-06-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0163_auto_20220612_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_provider_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='infrastructure_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='service_provider_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
