# Generated by Django 3.2.13 on 2022-08-20 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0163_auto_20220701_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='infrastructure_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runenvironment',
            name='infrastructure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='default_input_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='failure_report_probability',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='input_value_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_scheduling_managed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_service_managed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='managed_probability',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='output_value_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timeout_report_probability',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='auto_created_task_properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='error_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='execution_method_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='execution_method_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='infrastructure_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='infrastructure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='input_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='output_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runenvironment',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, choices=[('1.3.0', '1.3.0'), ('1.4.0', '1.4.0'), ('LATEST', 'LATEST')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, choices=[('1.3.0', '1.3.0'), ('1.4.0', '1.4.0'), ('LATEST', 'LATEST')], default='', max_length=10),
        ),
    ]
