# Generated by Django 3.2.13 on 2023-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0165_alter_taskexecution_execution_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runenvironment',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, choices=[('1.3.0', '1.3.0'), ('1.4.0', '1.4.0'), ('LATEST', 'LATEST')], default='1.4.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='aws_ecs_default_platform_version',
            field=models.CharField(blank=True, choices=[('1.3.0', '1.3.0'), ('1.4.0', '1.4.0'), ('LATEST', 'LATEST')], default='1.4.0', max_length=10),
        ),
    ]
