# Generated by Django 3.2.13 on 2023-01-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0166_auto_20230115_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='default_aws_ecs_configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
