# Generated by Django 3.2.13 on 2023-01-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0167_runenvironment_default_aws_ecs_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='runenvironment',
            name='aws_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
