# Generated by Django 3.2.18 on 2023-05-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0170_auto_20230204_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runenvironment',
            name='aws_ecs_default_assign_public_ip',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='aws_ecs_default_assign_public_ip',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
