# Generated by Django 3.2.21 on 2023-12-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0171_auto_20230519_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='build_task_execution',
            field=models.ForeignKey(blank=True, db_column='build_task_execution_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processes.taskexecution', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='deployment_task_execution',
            field=models.ForeignKey(blank=True, db_column='deployment_task_execution_uuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processes.taskexecution', to_field='uuid'),
        ),
    ]
