# Generated by Django 3.2.21 on 2024-01-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0172_auto_20231204_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='last_app_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
