# Generated by Django 4.2.11 on 2024-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0173_taskexecution_last_app_heartbeat_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="required_success_count_to_clear_failure",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="required_success_count_to_clear_timeout",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="required_success_count_to_clear_failure",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="required_success_count_to_clear_timeout",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
