# Generated by Django 4.2.11 on 2024-04-28 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0174_task_required_success_count_to_clear_failure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("type", models.CharField(choices=[], db_index=True, max_length=255)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_at", models.DateTimeField(auto_now_add=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.CharField(blank=True, max_length=50000)),
                ("resolved_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
