# Generated by Django 4.2.11 on 2024-04-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0177_taskexecutionevent_event_expected_heartbeat_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecutionStatusChangeEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.taskexecutionevent",),
        ),
        migrations.AddField(
            model_name="event",
            name="accelerated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="count_with_same_status_after_postponement",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="count_with_success_status_after_postponement",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="postponed_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("processes.heartbeatdetectionevent", "heartbeat detection event"),
                    ("processes.taskexecutionevent", "task execution event"),
                    (
                        "processes.taskexecutionstatuschangeevent",
                        "task execution status change event",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
