# Generated by Django 4.2.11 on 2024-05-13 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0178_taskexecutionstatuschangeevent_event_accelerated_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HeartbeatDetectionAlert",
            new_name="LegacyHeartbeatDetectionAlert",
        ),
        migrations.AlterModelTable(
            name="legacyheartbeatdetectionalert",
            table="processes_heartbeatdetectionalert",
        ),
    ]
