# Generated by Django 4.2.14 on 2024-09-03 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0180_notification_notificationdeliverymethod_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationDeliveryMethod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.notificationdeliverymethod",),
        ),
        migrations.CreateModel(
            name="PagerDutyNotificationDeliveryMethod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.notificationdeliverymethod",),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="email_bcc_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="email_cc_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="email_to_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="pagerduty_api_key",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="pagerduty_event_class_template",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="pagerduty_event_component_template",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="pagerduty_event_group_template",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="notificationdeliverymethod",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "processes.emailnotificationdeliverymethod",
                        "email notification delivery method",
                    ),
                    (
                        "processes.pagerdutynotificationdeliverymethod",
                        "pager duty notification delivery method",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
