# Generated by Django 4.2.16 on 2024-11-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0182_convert_notification_profiles"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InsufficientServiceInstancesEvent",
            new_name="LegacyInsufficientServiceInstancesEvent",
        ),
        migrations.AlterModelOptions(
            name="legacyinsufficientserviceinstancesevent",
            options={"ordering": ["detected_at"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="run_environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="processes.runenvironment",
            ),
        ),
        migrations.AlterModelTable(
            name="legacyinsufficientserviceinstancesevent",
            table="processes_insufficientserviceinstancesevent",
        ),
    ]
