# Generated by Django 4.2.16 on 2024-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0185_alter_alertmethod_created_by_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delayedprocessstartalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="delayedprocessstartalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="insufficientserviceinstancesalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="insufficientserviceinstancesalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="legacyheartbeatdetectionalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="legacyheartbeatdetectionalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="missingscheduledtaskexecutionalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="missingscheduledtaskexecutionalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="missingscheduledworkflowexecutionalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="missingscheduledworkflowexecutionalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="taskexecutionalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="taskexecutionalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="workflowexecutionalert",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="workflowexecutionalert",
            name="send_result",
            field=models.CharField(blank=True, default="", max_length=50000),
        ),
    ]
