# Generated by Django 4.2.16 on 2024-12-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0186_alter_delayedprocessstartalert_error_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="accelerated_at",
            new_name="triggered_at",
        ),
        migrations.AddField(
            model_name="event",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processes.task",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processes.workflow",
            ),
        ),
    ]
