# Generated by Django 4.2.17 on 2025-01-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0187_rename_accelerated_at_event_triggered_at_event_task_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_events",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
