# Generated by Django 4.2.17 on 2025-01-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0188_subscriptionplan_max_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_notifications",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
