# Generated by Django 4.2.17 on 2025-01-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("processes", "0189_subscriptionplan_max_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_by_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["created_by_group", "event_at"],
                name="processes_e_created_1659e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_by_group", "attempted_at"],
                name="processes_n_created_babf97_idx",
            ),
        ),
    ]
