# Generated by Django 4.2.18 on 2025-02-12 07:24

import os

from django.db import migrations


web_db_username = os.environ["WEB_DATABASE_USER"]


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0190_event_created_by_group_notification_created_by_group_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(sql=f"""
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC TO {web_db_username};
""",
        reverse_sql=migrations.RunSQL.noop),

        migrations.RunSQL(sql=f"""
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {web_db_username};
""",
        reverse_sql=migrations.RunSQL.noop),

        migrations.RunSQL(sql=f"""
GRANT USAGE ON ALL SEQUENCES IN SCHEMA PUBLIC TO {web_db_username};
""",
        reverse_sql=migrations.RunSQL.noop),

        migrations.RunSQL(sql=f"""
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT USAGE ON SEQUENCES TO {web_db_username};
""",
        reverse_sql=migrations.RunSQL.noop),
    ]
