# Generated by Django 4.2.18 on 2025-03-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0191_auto_20250212_0724"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.event",),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("processes.basicevent", "basic event"),
                    (
                        "processes.executionstatuschangeevent",
                        "execution status change event",
                    ),
                    (
                        "processes.missingheartbeatdetectionevent",
                        "missing heartbeat detection event",
                    ),
                    ("processes.taskexecutionevent", "task execution event"),
                    (
                        "processes.taskexecutionstatuschangeevent",
                        "task execution status change event",
                    ),
                    ("processes.workflowexecutionevent", "workflow execution event"),
                    (
                        "processes.workflowexecutionstatuschangeevent",
                        "workflow execution status change event",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="infrastructure_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
