# Generated by Django 4.2.18 on 2025-03-21 01:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0193_task_api_error_timeout_seconds_and_more"),
    ]

    operations = [
        migrations.RunSQL(sql="""
UPDATE processes_processexecution SET status_update_interval_seconds = NULL
where status_update_interval_seconds < 0
        """, reverse_sql=migrations.RunSQL.noop),
    ]
