# Generated by Django 4.2.20 on 2025-06-13 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0194_auto_20250321_0152"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="should_clear_failure_alerts_on_success",
        ),
        migrations.RemoveField(
            model_name="task",
            name="should_clear_timeout_alerts_on_success",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="should_clear_failure_alerts_on_success",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="should_clear_timeout_alerts_on_success",
        ),
    ]
