# Generated by Django 4.2.20 on 2025-07-02 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0195_remove_task_should_clear_failure_alerts_on_success_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legacyheartbeatdetectionevent",
            name="task_execution",
        ),
        migrations.DeleteModel(
            name="LegacyHeartbeatDetectionAlert",
        ),
        migrations.DeleteModel(
            name="LegacyHeartbeatDetectionEvent",
        ),
    ]
