# Generated by Django 4.2.20 on 2025-07-02 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0196_remove_legacyheartbeatdetectionevent_task_execution_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MissingScheduledTaskExecution",
            new_name="LegacyMissingScheduledTaskExecution",
        ),
        migrations.RenameModel(
            old_name="MissingScheduledTaskExecutionAlert",
            new_name="LegacyMissingScheduledTaskExecutionAlert",
        ),
        migrations.RenameModel(
            old_name="MissingScheduledWorkflowExecution",
            new_name="LegacyMissingScheduledWorkflowExecution",
        ),
        migrations.RenameModel(
            old_name="MissingScheduledWorkflowExecutionAlert",
            new_name="LegacyMissingScheduledWorkflowExecutionAlert",
        ),
    ]
