# Generated by Django 4.2.20 on 2025-07-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0197_rename_missingscheduledtaskexecution_legacymissingscheduledtaskexecution_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.event",),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("processes.basicevent", "basic event"),
                    (
                        "processes.executionstatuschangeevent",
                        "execution status change event",
                    ),
                    (
                        "processes.missingheartbeatdetectionevent",
                        "missing heartbeat detection event",
                    ),
                    ("processes.taskevent", "task event"),
                    ("processes.taskexecutionevent", "task execution event"),
                    (
                        "processes.taskexecutionstatuschangeevent",
                        "task execution status change event",
                    ),
                    ("processes.workflowexecutionevent", "workflow execution event"),
                    (
                        "processes.workflowexecutionstatuschangeevent",
                        "workflow execution status change event",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
