# Generated by Django 4.2.23 on 2025-08-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0198_taskevent_alter_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulableInstanceEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.event",),
        ),
        migrations.AlterModelOptions(
            name="missingheartbeatdetectionevent",
            options={"ordering": ["event_at", "detected_at"]},
        ),
        migrations.AddField(
            model_name="event",
            name="expected_execution_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="schedule",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("processes.basicevent", "basic event"),
                    (
                        "processes.executionstatuschangeevent",
                        "execution status change event",
                    ),
                    (
                        "processes.missingheartbeatdetectionevent",
                        "missing heartbeat detection event",
                    ),
                    (
                        "processes.missingscheduledexecutionevent",
                        "missing scheduled execution event",
                    ),
                    (
                        "processes.missingscheduledtaskexecutionevent",
                        "missing scheduled task execution event",
                    ),
                    (
                        "processes.missingscheduledworkflowexecutionevent",
                        "missing scheduled workflow execution event",
                    ),
                    (
                        "processes.schedulableinstanceevent",
                        "schedulable instance event",
                    ),
                    ("processes.taskevent", "task event"),
                    ("processes.taskexecutionevent", "task execution event"),
                    (
                        "processes.taskexecutionstatuschangeevent",
                        "task execution status change event",
                    ),
                    ("processes.workflowevent", "workflow event"),
                    ("processes.workflowexecutionevent", "workflow execution event"),
                    (
                        "processes.workflowexecutionstatuschangeevent",
                        "workflow execution status change event",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="MissingScheduledExecutionEvent",
            fields=[],
            options={
                "ordering": ["event_at", "detected_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.schedulableinstanceevent",),
        ),
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.schedulableinstanceevent",),
        ),
        migrations.CreateModel(
            name="MissingScheduledTaskExecutionEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "processes.taskexecutionevent",
                "processes.missingscheduledexecutionevent",
            ),
        ),
        migrations.CreateModel(
            name="MissingScheduledWorkflowExecutionEvent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "processes.workflowexecutionevent",
                "processes.missingscheduledexecutionevent",
            ),
        ),
    ]
