# Generated by Django 4.2.23 on 2025-08-14 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0199_schedulableinstanceevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="started_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="started_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
