# Generated by Django 4.2.23 on 2025-08-17 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0200_alter_taskexecution_started_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="schedule_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="schedule_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
