# Generated by Django 4.2.23 on 2025-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0201_alter_task_schedule_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="missing_execution_count",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
