# Generated by Django 4.2.23 on 2025-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0203_workflow_failure_report_probability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expected_heartbeat_at",
            field=models.DateTimeField(null=True),
        ),
    ]
