# Generated by Django 4.2.23 on 2025-11-25 01:11

from django.db import migrations


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY must run outside a transaction
    atomic = False

    dependencies = [
        ("processes", "0204_alter_event_expected_heartbeat_at"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "processes_event_task_event_at_idx ON processes_event (task_id, event_at);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS processes_event_task_event_at_idx;"
            ),
        ),
    ]
