# Generated by Django 4.2.23 on 2025-11-25 01:20

from django.db import migrations


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY must run outside a transaction
    atomic = False

    dependencies = [
        ("processes", "0205_create_taskid_eventat_index"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                "processes_event_workflow_event_at_idx ON processes_event (workflow_id, event_at);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS processes_event_workflow_event_at_idx;"
            ),
        ),
    ]