# Generated by Django 4.2.23 on 2025-12-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0206_create_workflowid_eventat_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="exception_message",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="exception_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="rate_limit_max_requests_per_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="rate_limit_max_severity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="rate_limit_request_period_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="rate_limit_tier_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_0",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_1",
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_2",
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_4",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_5",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_6",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_requests_per_period_7",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_0",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_4",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_5",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_6",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="max_severity_7",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_0",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_4",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_5",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_6",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_count_in_period_7",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_0",
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_1",
            field=models.PositiveIntegerField(blank=True, default=3600, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_2",
            field=models.PositiveIntegerField(blank=True, default=86400, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_4",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_5",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_6",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_seconds_7",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_0",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_1",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_2",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_3",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_4",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_5",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_6",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="request_period_started_at_7",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
