# Generated by Django 4.2.23 on 2026-01-01 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0207_notification_exception_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="detected_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
