# Generated by Django 4.2.23 on 2026-01-01 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0208_alter_event_detected_at_alter_event_event_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="attempted_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
