# Generated by Django 4.2.23 on 2026-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0210_notification_created_at_notification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdeliverymethod',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
