# Generated by Django 4.2.23 on 2026-01-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0211_notificationdeliverymethod_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsufficientServiceTaskExecutionsEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('processes.taskevent',),
        ),
        migrations.AddField(
            model_name='event',
            name='detected_concurrency',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='interval_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='interval_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='required_concurrency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('processes.basicevent', 'basic event'), ('processes.executionstatuschangeevent', 'execution status change event'), ('processes.insufficientservicetaskexecutionsevent', 'insufficient service task executions event'), ('processes.missingheartbeatdetectionevent', 'missing heartbeat detection event'), ('processes.missingscheduledexecutionevent', 'missing scheduled execution event'), ('processes.missingscheduledtaskexecutionevent', 'missing scheduled task execution event'), ('processes.missingscheduledworkflowexecutionevent', 'missing scheduled workflow execution event'), ('processes.schedulableinstanceevent', 'schedulable instance event'), ('processes.taskevent', 'task event'), ('processes.taskexecutionevent', 'task execution event'), ('processes.taskexecutionstatuschangeevent', 'task execution status change event'), ('processes.workflowevent', 'workflow event'), ('processes.workflowexecutionevent', 'workflow execution event'), ('processes.workflowexecutionstatuschangeevent', 'workflow execution status change event')], db_index=True, max_length=255),
        ),
    ]
