# Generated by Django 4.2.23 on 2026-01-23 08:19

from django.db import migrations, models
import processes.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0212_insufficientservicetaskexecutionsevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_event_severity_on_insufficient_instances',
            field=models.PositiveIntegerField(blank=True, default=400, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_event_severity_on_sufficient_instances_restored',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='notification_event_severity_on_insufficient_instances',
            field=models.PositiveIntegerField(blank=True, default=400, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='notification_event_severity_on_sufficient_instances_restored',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
    ]
