# Generated by Django 4.2.23 on 2026-01-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0213_task_notification_event_severity_on_insufficient_instances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='run_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processes.runenvironment'),
        ),
    ]
