# Generated by Django 4.2.23 on 2026-02-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0215_alter_delayedprocessstartdetectionevent_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
