# Generated by Django 4.2.23 on 2026-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0216_event_acknowledged_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['run_environment', 'event_at'], name='processes_e_run_env_8ec567_idx'),
        ),
    ]
