# Generated by Django 4.2.23 on 2026-02-13 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0224_event_created_at_event_created_by_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missingheartbeatdetectionevent",
            options={"ordering": ["event_at", "detected_at", "created_at"]},
        ),
    ]
