# Generated by Django 4.2.23 on 2026-02-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0225_alter_missingheartbeatdetectionevent_options"),
    ]

    operations = [
        # ExecutionStatusChangeEvent was previously registered as a proxy model
        # in migration state, but it's actually a plain Python mixin class.
        # We need to first re-register WorkflowExecutionStatusChangeEvent
        # without the ExecutionStatusChangeEvent base, then delete the model.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="WorkflowExecutionStatusChangeEvent",
                ),
                migrations.DeleteModel(
                    name="ExecutionStatusChangeEvent",
                ),
                migrations.CreateModel(
                    name="WorkflowExecutionStatusChangeEvent",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("processes.workflowexecutionevent",),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("processes.basicevent", "basic event"),
                    (
                        "processes.delayedtaskexecutionstartevent",
                        "delayed task execution start event",
                    ),
                    (
                        "processes.insufficientservicetaskexecutionsevent",
                        "insufficient service task executions event",
                    ),
                    (
                        "processes.missingheartbeatdetectionevent",
                        "missing heartbeat detection event",
                    ),
                    (
                        "processes.missingscheduledtaskexecutionevent",
                        "missing scheduled task execution event",
                    ),
                    (
                        "processes.missingscheduledworkflowexecutionevent",
                        "missing scheduled workflow execution event",
                    ),
                    ("processes.taskevent", "task event"),
                    ("processes.taskexecutionevent", "task execution event"),
                    (
                        "processes.taskexecutionstatuschangeevent",
                        "task execution status change event",
                    ),
                    ("processes.workflowevent", "workflow event"),
                    ("processes.workflowexecutionevent", "workflow execution event"),
                    (
                        "processes.workflowexecutionstatuschangeevent",
                        "workflow execution status change event",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
