# Generated by Django 4.2.29 on 2026-03-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0228_taskexecution_task_started_at_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskexecution',
            name='processes_taskexec_task_started_at_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='process_command',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='process_command',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
