# Generated by Django 4.2.29 on 2026-03-12 21:50

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('processes', '0229_remove_taskexecution_processes_taskexec_task_started_at_idx_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='event',
            index=models.Index(fields=['postponed_until'], name='processes_e_postpon_ec666f_idx'),
        ),
    ]
