# Generated by Django 4.2.29 on 2026-03-13 23:22, edited to be concurrent

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("processes", "0230_event_processes_e_postpon_ec666f_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="taskexecution",
            index=models.Index(
                fields=["task", "started_at"],
                name="taskexec_task_started_at_idx"
            ),
        ),
    ]
