# Generated by Django 5.2.12 on 2026-03-23 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0231_taskexecution_taskexec_task_started_at_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowexecution',
            options={'ordering': ['started_at']},
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'started_at'], name='workflowexec_wf_started_at_idx'),
        ),
    ]
