# Generated by Django 5.2.13 on 2026-04-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0232_alter_workflowexecution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_main_container_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_arn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_deploy_enable_circuit_breaker',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_deploy_maximum_percent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_deploy_minimum_healthy_percent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_deploy_rollback_on_failure',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_enable_ecs_managed_tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_force_new_deployment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_load_balancer_health_check_grace_period_seconds',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_propagate_tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_service_tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_task_definition_arn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_event_target_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_event_target_rule_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_scheduled_event_rule_arn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_scheduled_execution_rule_name',
        ),
    ]
