# Generated by Django 5.2.13 on 2026-04-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0233_remove_task_aws_ecs_main_container_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='aws_default_subnets',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_assign_public_ip',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_cluster_arn',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_execution_role',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_launch_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_platform_version',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_security_groups',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_default_task_role',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_enable_ecs_managed_tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_ecs_supported_launch_types',
        ),
        migrations.RemoveField(
            model_name='task',
            name='aws_tags',
        ),
    ]
