# Generated by Django 5.2.13 on 2026-04-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0234_remove_task_aws_default_subnets_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwsEcsServiceLoadBalancerDetails',
        ),
    ]
