# Generated by Django 5.2.13 on 2026-04-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0235_delete_awsecsserviceloadbalancerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_assign_public_ip',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_cluster_arn',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_execution_role',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_launch_type',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_platform_version',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_security_groups',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_task_arn',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_task_definition_arn',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_ecs_task_role',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_subnets',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='aws_tags',
        ),
    ]
