# Generated by Django 5.2.13 on 2026-04-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0236_remove_taskexecution_aws_ecs_assign_public_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_access_key',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_account_id',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_assumed_role_external_id',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_default_region',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_default_subnets',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_assign_public_ip',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_cluster_arn',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_execution_role',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_launch_type',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_platform_version',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_security_groups',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_default_task_role',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_enable_ecs_managed_tags',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_ecs_supported_launch_types',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_events_role_arn',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_secret_key',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_tags',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_workflow_starter_access_key',
        ),
        migrations.RemoveField(
            model_name='runenvironment',
            name='aws_workflow_starter_lambda_arn',
        ),
    ]
