# Generated by Django 5.2.13 on 2026-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0237_remove_runenvironment_aws_access_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppriseNotificationDeliveryMethod",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("processes.notificationdeliverymethod",),
        ),
        migrations.AddField(
            model_name="notificationdeliverymethod",
            name="apprise_url",
            field=models.CharField(
                help_text="URL for an Apprise notification service (e.g., 'slack://xoxb-token-here/C123456/U123456'). May contain placeholders in braces (e.g., '{token}').",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationdeliverymethod",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "processes.apprisenotificationdeliverymethod",
                        "apprise notification delivery method",
                    ),
                    (
                        "processes.emailnotificationdeliverymethod",
                        "email notification delivery method",
                    ),
                    (
                        "processes.pagerdutynotificationdeliverymethod",
                        "pager duty notification delivery method",
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
