# Generated by Django 5.2.14 on 2026-05-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0238_apprise_notification_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notification_profiles',
            field=models.ManyToManyField(blank=True, to='processes.notificationprofile'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='notification_profiles',
            field=models.ManyToManyField(blank=True, to='processes.notificationprofile'),
        ),
    ]
