# Generated by Django 5.2.14 on 2026-05-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0239_alter_task_notification_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runenvironment',
            name='notification_profiles',
            field=models.ManyToManyField(blank=True, to='processes.notificationprofile'),
        ),
    ]
