export const TASK_EXECUTION_STATUS_RUNNING = 'RUNNING';
export const TASK_EXECUTION_STATUS_MANUALLY_STARTED = 'MANUALLY_STARTED';
export const TASK_EXECUTION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const TASK_EXECUTION_STATUS_FAILED = 'FAILED';
export const TASK_EXECUTION_STATUS_STOPPING = 'STOPPING';
export const TASK_EXECUTION_STATUS_STOPPED = 'STOPPED';
export const TASK_EXECUTION_STATUS_ABANDONED = 'ABANDONED';
export const TASK_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT = 'TERMINATED_AFTER_TIME_OUT';
export const TASK_EXECUTION_STATUS_ABORTED = 'ABORTED';

export const TASK_EXECUTION_STATUSES = [
  TASK_EXECUTION_STATUS_MANUALLY_STARTED,
  TASK_EXECUTION_STATUS_RUNNING,
  TASK_EXECUTION_STATUS_SUCCEEDED,
  TASK_EXECUTION_STATUS_STOPPING,
  TASK_EXECUTION_STATUS_STOPPED,
  TASK_EXECUTION_STATUS_FAILED,
  TASK_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT,
  TASK_EXECUTION_STATUS_ABANDONED
];

export const TASK_EXECUTION_STATUSES_WITH_PROBLEMS = [
  TASK_EXECUTION_STATUS_FAILED,
  TASK_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT,
  TASK_EXECUTION_STATUS_ABANDONED
];

export const TASK_EXECUTION_STATUSES_IN_PROGRESS = [
  TASK_EXECUTION_STATUS_MANUALLY_STARTED,
  TASK_EXECUTION_STATUS_RUNNING
];

export const WORKFLOW_EXECUTION_STATUS_RUNNING = 'RUNNING';
export const WORKFLOW_EXECUTION_STATUS_MANUALLY_STARTED = 'MANUALLY_STARTED';
export const WORKFLOW_EXECUTION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const WORKFLOW_EXECUTION_STATUS_FAILED = 'FAILED';
export const WORKFLOW_EXECUTION_STATUS_STOPPING = 'STOPPING';
export const WORKFLOW_EXECUTION_STATUS_STOPPED = 'STOPPED';
export const WORKFLOW_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT = 'TERMINATED_AFTER_TIME_OUT';

export const WORKFLOW_EXECUTION_STATUSES_IN_PROGRESS = [
  WORKFLOW_EXECUTION_STATUS_MANUALLY_STARTED,
  WORKFLOW_EXECUTION_STATUS_RUNNING
];

export const WORKFLOW_EXECUTION_STATUSES = [
  WORKFLOW_EXECUTION_STATUS_RUNNING,
  WORKFLOW_EXECUTION_STATUS_MANUALLY_STARTED,
  WORKFLOW_EXECUTION_STATUS_SUCCEEDED,
  WORKFLOW_EXECUTION_STATUS_FAILED,
  WORKFLOW_EXECUTION_STATUS_STOPPING,
  WORKFLOW_EXECUTION_STATUS_STOPPED,
  WORKFLOW_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT
];

export const WORKFLOW_EXECUTION_STATUSES_WITH_PROBLEMS = [
  WORKFLOW_EXECUTION_STATUS_FAILED,
  WORKFLOW_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT
];

export const START_TRANSITION_CONDITIONS_ALL = 'all';
export const START_TRANSITION_CONDITIONS_ANY = 'any';
export const START_TRANSITION_CONDITIONS_COUNT_AT_LEAST = 'count_at_least';
export const START_TRANSITION_CONDITIONS_RATIO_AT_LEAST = 'ratio_at_least';

export const TASK_FAILURE_BEHAVIOR_FAIL_WORKFLOW_ALWAYS = 'always_fail_workflow';
export const TASK_FAILURE_BEHAVIOR_FAIL_WORKFLOW_IF_UNHANDLED = 'fail_workflow_if_unhandled';
export const TASK_FAILURE_BEHAVIOR_IGNORE = 'ignore';

export const TASK_EXECUTION_STATUS_FAIL_WORKFLOW_ALWAYS = 'always_fail_workflow';
export const TASK_EXECUTION_STATUS_TIMEOUT_WORKFLOW_ALWAYS = 'always_timeout_workflow';
export const TASK_EXECUTION_STATUS_FAIL_WORKFLOW_IF_UNHANDLED = 'fail_workflow_if_unhandled';
export const TASK_EXECUTION_STATUS_TIMEOUT_WORKFLOW_IF_UNHANDLED = 'timeout_workflow_if_unhandled';
export const TASK_EXECUTION_STATUS_IGNORE = 'ignore';


export const ACCESS_LEVEL_OBSERVER = 1;
export const ACCESS_LEVEL_TASK = 50;
export const ACCESS_LEVEL_SUPPORT = 100;
export const ACCESS_LEVEL_DEVELOPER = 500;
export const ACCESS_LEVEL_ADMIN = 1000;

export const ACCESS_LEVEL_OBSERVER_ROLE_NAME = 'Observer';

export const ACCESS_LEVEL_TO_ROLE_NAME = {
  ['' + ACCESS_LEVEL_OBSERVER]: ACCESS_LEVEL_OBSERVER_ROLE_NAME,
  ['' + ACCESS_LEVEL_TASK]:  'Task',
  ['' + ACCESS_LEVEL_SUPPORT]:  'Support',
  ['' + ACCESS_LEVEL_DEVELOPER]:  'Developer',
  ['' + ACCESS_LEVEL_ADMIN]: 'Admin'
};

export const EXECUTION_METHOD_TYPE_AWS_ECS = 'AWS ECS';
export const EXECUTION_METHOD_TYPE_AWS_LAMBDA = 'AWS Lambda';
export const EXECUTION_METHOD_TYPE_AWS_CODEBUILD = 'AWS CodeBuild';
export const EXECUTION_METHOD_TYPE_UNKNOWN = 'Unknown';

export const EXECUTION_CAPABILITY_MANUAL_START = 'MANUAL_START';
export const EXECUTION_CAPABILITY_SCHEDULING = 'SCHEDULING';
export const EXECUTION_CAPABILITY_SETUP_SERVICE = 'SETUP_SERVICE';

export const DEFAULT_NAME = '__default__';

export const INFRASTRUCTURE_TYPE_AWS = 'AWS';

export const AWS_REGIONS = [
  'us-east-1',
  'us-east-2',
  'us-west-1',
  'us-west-2',
  'us-gov-east-1',
  'us-gov-west-1',
  'ap-west-1',
  'ap-south-1',
  'ap-northeast-1',
  'ap-northeast-2',
  'ap-northeast-3',
  'eu-central-1',
  'eu-west-1',
  'eu-west-2',
  'eu-west-3',
  'eu-north-1',
  'me-south-1',
  'sa-east-1',
  'ca-central-1',
  'cn-north-1',
  'cn-northwest-1'
];

const AWS_ACCOUNT_ID_REGEXP_CHARS = "\\d{12}";
const AWS_REGION_REGEXP_CHARS = AWS_REGIONS.join('|');
const AWS_ARN_REGEXP_PREFIX = '^arn:aws(-us-gov)?:';
const LOWER_HEX_DIGIT_REGEXP_CHAR = "[0-9a-f]";

export const AWS_ACCOUNT_ID_REGEXP = new RegExp('^' + AWS_ACCOUNT_ID_REGEXP_CHARS + '$');
export const AWS_ROLE_ARN_REGEXP = new RegExp('(' + AWS_ARN_REGEXP_PREFIX + 'iam::' +
  AWS_ACCOUNT_ID_REGEXP_CHARS + ':role/)?[\\w-]+$');
export const AWS_SUBNET_REGEXP = new RegExp('^subnet-(' +
  LOWER_HEX_DIGIT_REGEXP_CHAR + '{8}|' +
  LOWER_HEX_DIGIT_REGEXP_CHAR + '{17})$');

export const AWS_SECURITY_GROUP_REGEXP = new RegExp('^sg-(' +
  LOWER_HEX_DIGIT_REGEXP_CHAR + '{8}|' +
  LOWER_HEX_DIGIT_REGEXP_CHAR + '{17})$');

export const AWS_LAMBDA_ARN_REGEXP = new RegExp('(' + AWS_ARN_REGEXP_PREFIX +
  "lambda:(" + AWS_REGION_REGEXP_CHARS + '):' + AWS_ACCOUNT_ID_REGEXP_CHARS +
  ":function:)?[\\w-]+(:\\d+)?$");

export const AWS_ECS_CLUSTER_ARN_REGEXP = new RegExp('(' + AWS_ARN_REGEXP_PREFIX +
  'ecs:(' + AWS_REGION_REGEXP_CHARS + '):' + AWS_ACCOUNT_ID_REGEXP_CHARS +
  ':cluster/)?[\\w-.]{1,255}$');

export const AWS_ECS_LAUNCH_TYPE_FARGATE = 'FARGATE';
export const AWS_ECS_LAUNCH_TYPE_EC2 = 'EC2';
export const AWS_ECS_LAUNCH_TYPE_EXTERNAL = 'EXTERNAL';
export const AWS_ECS_ALL_SUPPORTED_LAUNCH_TYPES = [
  AWS_ECS_LAUNCH_TYPE_FARGATE,
  AWS_ECS_LAUNCH_TYPE_EC2,
  AWS_ECS_LAUNCH_TYPE_EXTERNAL
];
export const AWS_ECS_PLATFORM_VERSIONS = [
  '1.3.0',
  '1.4.0',
  'LATEST'
];
export const SERVICE_PROVIDER_AWS_ECS = 'AWS ECS';