export const TASK_EXECUTION_STATUS_RUNNING = 'RUNNING';
export const TASK_EXECUTION_STATUS_MANUALLY_STARTED = 'MANUALLY_STARTED';
export const TASK_EXECUTION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const TASK_EXECUTION_STATUS_FAILED = 'FAILED';
export const TASK_EXECUTION_STATUS_STOPPING = 'STOPPING';
export const TASK_EXECUTION_STATUS_STOPPED = 'STOPPED';
export const TASK_EXECUTION_STATUS_ABANDONED = 'ABANDONED';
export const TASK_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT = 'TERMINATED_AFTER_TIME_OUT';
export const TASK_EXECUTION_STATUS_ABORTED = 'ABORTED';

export const TASK_EXECUTION_STATUSES_WITH_PROBLEMS = [
  TASK_EXECUTION_STATUS_FAILED,
  TASK_EXECUTION_STATUS_ABORTED,
  TASK_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT,
  TASK_EXECUTION_STATUS_ABANDONED
]

export const TASK_EXECUTION_STATUSES_IN_PROGRESS = [
  TASK_EXECUTION_STATUS_MANUALLY_STARTED,
  TASK_EXECUTION_STATUS_RUNNING
];

export const WORKFLOW_EXECUTION_STATUS_RUNNING = 'RUNNING';
export const WORKFLOW_EXECUTION_STATUS_MANUALLY_STARTED = 'MANUALLY_STARTED';
export const WORKFLOW_EXECUTION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const WORKFLOW_EXECUTION_STATUS_FAILED = 'FAILED';
export const WORKFLOW_EXECUTION_STATUS_STOPPING = 'STOPPING';
export const WORKFLOW_EXECUTION_STATUS_STOPPED = 'STOPPED';
export const WORKFLOW_EXECUTION_STATUS_TERMINATED_AFTER_TIME_OUT = 'TERMINATED_AFTER_TIME_OUT';

export const WORKFLOW_EXECUTION_STATUSES_IN_PROGRESS = [
  WORKFLOW_EXECUTION_STATUS_MANUALLY_STARTED,
  WORKFLOW_EXECUTION_STATUS_RUNNING
];

export const START_TRANSITION_CONDITIONS_ALL = 'all';
export const START_TRANSITION_CONDITIONS_ANY = 'any';
export const START_TRANSITION_CONDITIONS_COUNT_AT_LEAST = 'count_at_least';
export const START_TRANSITION_CONDITIONS_RATIO_AT_LEAST = 'ratio_at_least';

export const TASK_FAILURE_BEHAVIOR_FAIL_WORKFLOW_ALWAYS = 'always_fail_workflow';
export const TASK_FAILURE_BEHAVIOR_FAIL_WORKFLOW_IF_UNHANDLED = 'fail_workflow_if_unhandled';
export const TASK_FAILURE_BEHAVIOR_IGNORE = 'ignore';

export const TASK_EXECUTION_STATUS_FAIL_WORKFLOW_ALWAYS = 'always_fail_workflow';
export const TASK_EXECUTION_STATUS_TIMEOUT_WORKFLOW_ALWAYS = 'always_timeout_workflow';
export const TASK_EXECUTION_STATUS_FAIL_WORKFLOW_IF_UNHANDLED = 'fail_workflow_if_unhandled';
export const TASK_EXECUTION_STATUS_TIMEOUT_WORKFLOW_IF_UNHANDLED = 'timeout_workflow_if_unhandled';
export const TASK_EXECUTION_STATUS_IGNORE = 'ignore';


export const ACCESS_LEVEL_OBSERVER = 1;
export const ACCESS_LEVEL_TASK = 50;
export const ACCESS_LEVEL_SUPPORT = 100;
export const ACCESS_LEVEL_DEVELOPER = 500;
export const ACCESS_LEVEL_ADMIN = 1000;

export const ACCESS_LEVEL_OBSERVER_ROLE_NAME = 'Observer';

export const ACCESS_LEVEL_TO_ROLE_NAME = {
  ['' + ACCESS_LEVEL_OBSERVER]: ACCESS_LEVEL_OBSERVER_ROLE_NAME,
  ['' + ACCESS_LEVEL_TASK]:  'Task',
  ['' + ACCESS_LEVEL_SUPPORT]:  'Support',
  ['' + ACCESS_LEVEL_DEVELOPER]:  'Developer',
  ['' + ACCESS_LEVEL_ADMIN]: 'Admin'
};

export const EXECUTION_METHOD_TYPE_AWS_ECS = 'AWS ECS';
export const EXECUTION_METHOD_TYPE_AWS_LAMBDA = 'AWS Lambda';
export const EXECUTION_METHOD_TYPE_UNKNOWN = 'Unknown';

export const EXECUTION_CAPABILITY_MANUAL_START = 'MANUAL_START';
export const EXECUTION_CAPABILITY_SCHEDULING = 'SCHEDULING';
export const EXECUTION_CAPABILITY_SETUP_SERVICE = 'SETUP_SERVICE';
